import { sidebar } from "vuepress-theme-hope";

export const enSidebar = sidebar({
  "/en/": false,

  "/en/guide/": [
    "introduce",
    {
      text: "Getting started",
      icon: "leibie",
      prefix: "getstarted/",
      collapsible: true,
      children: [
        "start",
        "projectEnv",
        "dataMapping",
        "stringGenerationStrategy",
        "icon",
        "otherConfig",
        "shortcut",
      ],
    },
    "install",
    {
      text: "Features",
      icon: "featuresNew",
      prefix: "features/",
      link: "features/README.md",
      collapsible: true,
      children: [
        "makeIconMove",
        "projectLevelDomainConfig",
        "projectValueConfig",
        "searchEveryWhere",
        "apiGroup",
        "debugApi",
        "downloadApi",
        "stopRequest",
        "navigateCurrentMethod",
        "saveRequest",
        "tempRequest",
        "apifox",
        "postmanSync",
        "regenerate",
        "curlImport",
        "copyCurl",
        "copyUrl",
        "apiDocSync",
        "historyRequest",
        "settingManager",
        "fullScreen",
        "annualReport",
        "docAndContact",
        "htmlPreview",
        "swaggerDefaultValueParse",
        "autoDescription",
        "apiList",
        "apiToPostman",
        "apiImportExport",
        "batchExportApiDoc",
        "apiNavigateTree",
        "apiPreview",
        "apiCommentPreview",
        "script",
        "function",
        "quickAddHeader",
        "autoDomain",
        "ai",
        "headerGroup",
        "bulkEdit",
        "customToolbar",
        "jsonGrammarCheck",
      ],
    },
    "script",
    "features/environment",
    "history",
    "teamwork",
    "buy",
    "versionCompare",
    "concatGroup",
    "faq",
    "priceAdjust",
    "eula",
    "whatsnew",
    "feature",
  ],
});

export const zhSidebar = sidebar({
  "/en/": false,

  "/guide/": [
    "introduce",
    {
      text: "快速上手",
      icon: "leibie",
      prefix: "getstarted/",
      collapsible: true,
      children: [
        "start",
        "projectEnv",
        "dataMapping",
        "stringGenerationStrategy",
        "icon",
        "otherConfig",
        "shortcut",
      ],
    },
    "install",
    {
      text: "功能",
      icon: "featuresNew",
      prefix: "features/",
      collapsible: true,
      link: "/guide/features/README.md",
      children: [
        "makeIconMove",
        "projectLevelDomainConfig",
        "projectValueConfig",
        "searchEveryWhere",
        "apiGroup",
        "debugApi",
        "downloadApi",
        "stopRequest",
        "navigateCurrentMethod",
        "saveRequest",
        "tempRequest",
        "apifox",
        "postmanSync",
        "regenerate",
        "curlImport",
        "copyCurl",
        "copyUrl",
        "apiDocSync",
        "historyRequest",
        "settingManager",
        "fullScreen",
        "annualReport",
        "docAndContact",
        "htmlPreview",
        "swaggerDefaultValueParse",
        "autoDescription",
        "apiList",
        "apiToPostman",
        "apiImportExport",
        "batchExportApiDoc",
        "apiNavigateTree",
        "apiPreview",
        "apiCommentPreview",
        "script",
        "function",
        "quickAddHeader",
        "autoDomain",
        "ai",
        "headerGroup",
        "bulkEdit",
        "customToolbar",
        "jsonGrammarCheck",
      ],
    },
    "script",
    "features/environment",
    "history",
    "teamwork",
    "buy",
    "versionCompare",
    "concatGroup",
    "teachingVideo",
    "faq",
    "eula",
    "priceAdjust",
    "sponsorList",
    "activity",
    "link",
    "whatsnew",
    "feature",
  ],
});
